//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiderQc.Web.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.Comment1 = new HashSet<Comment>();
        }
    
        public int CommentId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int SenderId { get; set; }
        public Nullable<int> RideId { get; set; }
        public Nullable<int> TrajetId { get; set; }
        public string CommentText { get; set; }
        public bool Blocked { get; set; }
        public int Vote { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment1 { get; set; }
        public virtual Comment Comment2 { get; set; }
        public virtual Ride Ride { get; set; }
        public virtual User User { get; set; }
        public virtual Trajet Trajet { get; set; }
    }
}
