//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiderQc.Web.Entities
{
    using ViewModels.Moto;
    public partial class Moto
    {
        public Moto() { }
        public Moto(MotoViewModel motoViewModel)
        {
            Brand = motoViewModel.Brand;
            Model = motoViewModel.Model;
            Year = motoViewModel.Year;
            Type = motoViewModel.Type;
        }

        public Moto(MotoViewModel motoViewModel, int motoId)
        {
            Brand = motoViewModel.Brand;
            Model = motoViewModel.Model;
            Year = motoViewModel.Year;
            Type = motoViewModel.Type;
            MotoId = motoId;
        }

        public int MotoId { get; set; }
        public int UserId { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int? Year { get; set; }
        public int? Type { get; set; } 
        public virtual User User { get; set; }
    }
}
