//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiderQc.Web.Entities
{
    using RiderQc.Web.ViewModels.Ride;
    using System;
    using System.Collections.Generic;

    public partial class Ride
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ride()
        {
            this.Comments = new HashSet<Comment>();
            this.UserRides = new HashSet<UserRide>();
        }
        
        public int RideId { get; set; }
        public Nullable<int> TrajetId { get; set; }
        public int CreatorId { get; set; }
        public string Description { get; set; }
        public int LevelId { get; set; }
        public System.DateTime DateDepart { get; set; }
        public System.DateTime DateFin { get; set; }
        public string Title { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Level Level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRide> UserRides { get; set; }
        public virtual Trajet Trajet { get; set; }
        public virtual User User { get; set; }
    }
}
