//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiderQc.Web.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLevel
    {
        public int UserLevelId { get; set; }
        public int UserId { get; set; }
        public int LevelId { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual User User { get; set; }
    }
}
