//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiderQc.Web.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRating
    {
        public int UserRatingId { get; set; }
        public int RaterId { get; set; }
        public int RatedId { get; set; }
        public int Rate { get; set; }
        public string RatingMessage { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
